"""init

Revision ID: 58063c54cfba
Revises: 
Create Date: 2026-06-19 11:35:25.542118+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58063c54cfba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_size', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('default_risk_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_trades', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_daily_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_open_trades', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_user_id'), 'risk_profiles', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_appetite', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('actual_entry_price', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('actual_exit_price', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('risk_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('market_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('volatility', sa.String(length=50), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_contexts_trade_id'), 'market_contexts', ['trade_id'], unique=True)
    op.create_table('risk_calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('account_size', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('risk_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_calculations_trade_id'), 'risk_calculations', ['trade_id'], unique=True)
    op.create_table('rule_validations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('passed_rules', sa.JSON(), nullable=True),
    sa.Column('failed_rules', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_validations_trade_id'), 'rule_validations', ['trade_id'], unique=True)
    op.create_table('trade_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_notes_trade_id'), 'trade_notes', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_notes_trade_id'), table_name='trade_notes')
    op.drop_table('trade_notes')
    op.drop_index(op.f('ix_rule_validations_trade_id'), table_name='rule_validations')
    op.drop_table('rule_validations')
    op.drop_index(op.f('ix_risk_calculations_trade_id'), table_name='risk_calculations')
    op.drop_table('risk_calculations')
    op.drop_index(op.f('ix_market_contexts_trade_id'), table_name='market_contexts')
    op.drop_table('market_contexts')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_risk_profiles_user_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
